# Dataset Understanding

1. What are the rows and columns
2. which is column can be the target variable
3. what are the datatypes of the column
4. what means does the column infer

## Data Loading & Initial Inspection

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
data = pd.read_csv("train.csv")

In [7]:
data.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
list(data.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

PassengerId -> row number
Survived -> survived or not (1: yes, 0: no)
Pclass -> passenger class (can identify the survival rate of rich poor)
Name -> name of the passenger 
Sex -> gender of the passenger (can help in identifying the gender who survived most)
Age -> age of the passenger (can identify survival rate of age grp)
SibSp -> Sibling + Spouse count
Parch -> Parent + Children count
Ticket -> ticket id (People sharing the same ticket may belong to the same group or family.)
Fare -> price of the ticket (it reflects wealth and may correlate with survival.)
Cabin -> cabin number of the passengers (can be useful in identify that survival rate based on location of cabin (lower or upper))
Embarked -> boarding point

In [14]:
data.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [17]:
for values in list(data.columns):
    print(f"{values} count: {data[values].nunique()}")

PassengerId count: 891
Survived count: 2
Pclass count: 3
Name count: 891
Sex count: 2
Age count: 88
SibSp count: 7
Parch count: 7
Ticket count: 681
Fare count: 248
Cabin count: 147
Embarked count: 3

PassengerId -> Unique identifier (not useful for most analyses)

Survived -> Binary categorical variable

Pclass -> Ordinal categorical variable (1st, 2nd, 3rd class)

Name -> High-cardinality text feature (may extract titles)

Sex -> Binary categorical variable

Age -> Continuous numerical variable

SibSp -> Small discrete count variable

Parch -> Small discrete count variable

Ticket -> High-cardinality categorical feature; some passengers share tickets

Fare -> Continuous numerical variable

Cabin -> High-cardinality categorical feature; some passengers share cabins; many missing values

Embarked -> Categorical variable

In [19]:
data.shape

(891, 12)

In [20]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [22]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [26]:
data.describe(include= ["object", "string"])

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

count
1. Name: no missing values
2. Sex: no missing values
3. Ticket: no missing values
4. Cabin: only 204 data is present many values are missing
5. Embarked: most of the data is present only 2 values are missing

unique
1. sex: binary categorical
2. ticket: highly cardinal
3. cabin: highly cardinal
4. embarked: nominal categorical

top (mode)
1. Sex:
   Top value = male.

2. Cabin:
   Top value = G6.

3. Ticket:
   Top value = 347082.

4. Embarked:
   Top value = S.

freq (appearance count of the top values)
1. Sex:
   The value "male" appears 577 times.

2. Cabin:
   G6 appears 4 times.

3. Ticket:
   Ticket 347082 appears 7 times.

4. Embarked:
   S appears 644 times.

# Problem Statement & Hypothesis

### What does this dataset appear to represent?

### What are we trying to understand?

### What business/data questions can be asked?

### Initial hypotheses

# Data Cleaning

# EDA

# Visualisation

# Key Findings

# Final Conclusions

What I learnt